### ISSUE TITLE
More generic function to set source

### ISSUE THREAD

**Issue by jensrossbach** [johanpoirier/node-sony-audio-api#2]
Please add a more generic function to the souce of the device. Currently it is only possible to set the source to one of the HDMI external inputs and to the network audio service. It would be good to have a function that makes it possible to address all possible source types (e.g. tv, dlna, bt, ...).

**Comment by johanpoirier** [comment]
Hi,

You can check out version 0.2.1 of the lib.
You can set the source like that:
```
api.setSource('extInput', 'btAudio');
```
See https://developer.sony.com/develop/audio-control-api/api-references/device-uri for the various device resource uris.

**Comment by jensrossbach** [comment]
Perfect, thank you!
